/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.hadiel.aulafinalgit.view;

import com.hadiel.aulafinalgit.dao.EmprestimoDAO;
import com.hadiel.aulafinalgit.dao.LivroDAO;
import com.hadiel.aulafinalgit.dao.UsuarioDAO;
import com.hadiel.aulafinalgit.model.Emprestimo;
import com.hadiel.aulafinalgit.model.Livro;
import com.hadiel.aulafinalgit.model.Usuario;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author hadiel
 */
public class AdicionarEmprestimo extends javax.swing.JDialog {

    UsuarioDAO usuarioDAO;
    LivroDAO livroDAO;
    EmprestimoDAO emprestimoDAO;
    Emprestimo emprestimo;
    List<Usuario> usuarios;
    List<Livro> livros;
    int indexLivro = 0;
    int indexUsuario = 0;

    /**
     * Creates new form AdicionarEmprestimo
     *
     * @param parent
     * @param modal
     * @param emprestimo
     */
    public AdicionarEmprestimo(java.awt.Frame parent, boolean modal, Emprestimo emprestimo) {
        super(parent, modal);
        this.usuarioDAO = new UsuarioDAO();
        this.livroDAO = new LivroDAO();
        this.emprestimoDAO = new EmprestimoDAO();
        this.emprestimo = emprestimo;
        initComponents();
        preencherComboBoxUsuarios();
        preencherComboBoxLivros();

        jFormattedTextField1.setText(getDataHj());
        jFormattedTextField2.setText(calculaSeteDias(getDataHj()));

        jComboBox1.setSelectedIndex(indexLivro);
        jComboBox2.setSelectedIndex(indexUsuario);

        if (emprestimo != null) {
            jLabel1.setText("Edição de Empréstimo");
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(false);
        }

    }

    private void preencherComboBoxUsuarios() {
        jComboBox2.removeAllItems();
        usuarios = usuarioDAO.listarUsuarios(" ORDER BY nome");
        int cont = 0;
        for (Usuario usuario : usuarios) {
            if (emprestimo != null) {
                if (emprestimo.getUsuarioCodigo() == usuario.getId()) {
                    indexUsuario = cont;
                }
            }
            jComboBox2.addItem(usuario.getNome());
            cont++;
        }
    }

    private void preencherComboBoxLivros() {
        jComboBox1.removeAllItems();
        String disponivel = "true";
        if (emprestimo != null) {
            disponivel = "false";
        }
        livros = livroDAO.listarLivros(" WHERE disponivel = '" + disponivel + "' ORDER BY titulo");
        int cont = 0;
        for (Livro livro : livros) {
            if (emprestimo != null) {
                if (emprestimo.getLivroCodigo() == livro.getId()) {
                    indexUsuario = cont;
                }
            }
            jComboBox1.addItem(livro.getTitulo());
            cont++;
        }
    }

    public static String getDataHj() {
        // Obter a data atual
        LocalDate hoje = LocalDate.now();

        // Formatando a data atual para dd/MM/aaaa
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return hoje.format(formato);
    }

    public static String calculaSeteDias(String data) {
        // Converter a string de data para LocalDate
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataFormatada = LocalDate.parse(data, formato);

        // Adicionar 7 dias à data fornecida
        LocalDate dataDaquiA7Dias = dataFormatada.plusDays(7);

        // Formatando a nova data para dd/MM/aaaa
        return dataDaquiA7Dias.format(formato);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(":: Edição de Empréstimo");

        jLabel1.setText("Adicionar novo empréstimo");

        jLabel2.setText("Livro");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Usuário");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Data Locação");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusLost(evt);
            }
        });

        jLabel5.setText("Data Devolução");

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Status");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Emprestado");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Devolvido");

        jButton1.setText("Salvar Empréstimo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, 388, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField1)
                    .addComponent(jFormattedTextField2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusLost
        jFormattedTextField2.setText(calculaSeteDias(jFormattedTextField1.getText()));
    }//GEN-LAST:event_jFormattedTextField1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (emprestimo == null) {
            if (!emprestimoDAO.verificarPendencias(usuarios.get(jComboBox2.getSelectedIndex()).getId())) {
                emprestimo = new Emprestimo();
                emprestimo.setDataDevolucao(jFormattedTextField2.getText().trim());
                emprestimo.setDataLocacao(jFormattedTextField1.getText().trim());
                emprestimo.setLivroCodigo(livros.get(jComboBox1.getSelectedIndex()).getId());
                emprestimo.setUsuarioCodigo(usuarios.get(jComboBox2.getSelectedIndex()).getId());

                emprestimo.setStatus("Emprestado");
                if (jRadioButton2.isSelected()) {
                    emprestimo.setStatus("Disponível");
                }

                if (emprestimoDAO.realizarEmprestimo(emprestimo)) {
                    Livro livro = livros.get(jComboBox1.getSelectedIndex());
                    livro.setDisponivel(!jRadioButton1.isSelected());
                    livroDAO.editarLivro(livro);
                    dispose();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Esse usuário possui devoluções pendentes.", "Falha no Empréstimo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            emprestimo.setDataDevolucao(jFormattedTextField2.getText().trim());
            emprestimo.setDataLocacao(jFormattedTextField1.getText().trim());
            emprestimo.setLivroCodigo(livros.get(jComboBox1.getSelectedIndex()).getId());
            emprestimo.setUsuarioCodigo(usuarios.get(jComboBox2.getSelectedIndex()).getId());
            emprestimo.setStatus("Emprestado");
            if (jRadioButton2.isSelected()) {
                emprestimo.setStatus("Disponível");
                if (emprestimoDAO.atualizarEmprestimo(emprestimo)) {
                    Livro livro = livros.get(jComboBox1.getSelectedIndex());
                    livro.setDisponivel(true);
                    livroDAO.editarLivro(livro);
                    dispose();
                }
            } else {
                if (emprestimoDAO.atualizarEmprestimo(emprestimo)) {
                    dispose();
                }
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
