/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hadiel.aulafinalgit.view;

import com.hadiel.aulafinalgit.dao.EmprestimoDAO;
import com.hadiel.aulafinalgit.dao.LivroDAO;
import com.hadiel.aulafinalgit.dao.UsuarioDAO;
import com.hadiel.aulafinalgit.model.Emprestimo;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hadiel
 */
public class PainelEmprestimo extends javax.swing.JPanel {

    EmprestimoDAO emprestimoDAO;
    List<Emprestimo> listaEmprestimo;
    LivroDAO livroDAO;
    UsuarioDAO usuarioDAO;
    /**
     * Creates new form PainelEmprestimo
     */
    public PainelEmprestimo() {
        emprestimoDAO = new EmprestimoDAO();
        livroDAO = new LivroDAO();
        usuarioDAO = new UsuarioDAO();
        initComponents();
        atualizarTabela();
    }

    private void atualizarTabela() {
        listaEmprestimo = emprestimoDAO.listarEmprestimos(" WHERE status = 'Emprestado'");

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        model.addColumn("Código");
        model.addColumn("Livro");
        model.addColumn("Usuário");
        model.addColumn("Data Empréstimo");
        model.addColumn("Data Devolução");

        for (Emprestimo emprestimo : listaEmprestimo) {
            Object[] rowData = {emprestimo.getCodigo(), livroDAO.getLivroById(emprestimo.getLivroCodigo()).getTitulo(), usuarioDAO.getUsuarioById(emprestimo.getUsuarioCodigo()).getNome(), emprestimo.getDataLocacao(), emprestimo.getDataDevolucao()};
            model.addRow(rowData);
        }

        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Novo Empréstimo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(737, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdicionarEmprestimo adicao = new AdicionarEmprestimo(null, true, null);
        adicao.pack();
        adicao.setLocationRelativeTo(null);
        adicao.setVisible(true);
        atualizarTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            AdicionarEmprestimo adicao = new AdicionarEmprestimo(null, true, listaEmprestimo.get(jTable1.getSelectedRow()));
            adicao.pack();
            adicao.setLocationRelativeTo(null);
            adicao.setVisible(true);
            atualizarTabela();
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
